name: "Hola Mundo"
description: "Prints Hola Mundo"
author: "Edwin Einsen Vásquez Velásquez"

inputs:
  message:
    description: "Set the message to show"
    required: true
    default: "Sandy"

runs:
  using: "composite"

  steps:
    - name: Hola mundo
      run: echo "Hola ${{ inputs.message }}"
      shell: bash
