name: Hola mundo

# on: [push, pull_request]
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

  list:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: ls -al

  file:
    runs-on: ubuntu-latest
    needs: [list]
    steps:
      - name: Create file
        run: touch hola.txt

      - name: Add text
        run: echo "Hola mundo" >> hola.txt

      - name: Read file
        run: cat hola.txt
