name: Install Packages

on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: |
          chmod +x script.sh
          ./script.sh
          
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18
