name: Servicios

on: [push]

jobs:
  mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ vars.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Verify installation
        run: echo "El valor de mi variable de entorno es ${{ vars.MYSQL_ROOT_PASSWORD }}"

      - name: Secret
        run: echo "Mi SECRET es ${{ secrets.SECRET_FOR_ACTION }}"
